#!/usr/bin/env python3
"""Generate INVENTORY.md from static analysis + baseline timings + curated notes."""
import ast
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "webui"))
import registry as registry_mod  # noqa: E402

NOTES = (ROOT / "tools" / "inventory_notes.md").read_text(encoding="utf-8")


def notes_for(stem):
    """Pull the per-script section from inventory_notes.md if present."""
    m = re.search(rf"^## {re.escape(stem)}\.py.*?\n(.*?)(?=^## |\Z)", NOTES,
                  re.M | re.S)
    return m.group(1).strip() if m else None


def main():
    reg = registry_mod.build_registry()
    meta = json.loads((ROOT / "baseline" / "_meta.json").read_text(encoding="utf-8"))

    out = []
    out.append("# Test & Analysis Inventory\n")
    out.append("Generated by `tools/gen_inventory.py` from static analysis, the "
               "baseline run (`baseline/`), and the Phase-1 reading notes "
               "(`tools/inventory_notes.md` — full per-script commentary, bug log, "
               "and era groupings).\n")
    n_ok = sum(1 for v in meta.values() if v.get("status") == "ok")
    n_err = sum(1 for v in meta.values() if v.get("status") == "error")
    n_to = sum(1 for v in meta.values() if v.get("status") == "timeout")
    n_skip = sum(1 for v in meta.values() if v.get("status") == "skipped")
    out.append(f"**{len(reg)} runnable tests** · baseline: {n_ok} ok, {n_err} error, "
               f"{n_to} timeout, {n_skip} skipped (downloaders)\n")
    out.append("Data inputs: `folios/*.txt` (IVTFF EVA transcriptions, 201 folios), "
               "`data/latin_texts/`, `data/vernacular_texts/`, `data/czech_bible_kralice/`, "
               "`data/asian_texts/`, plus inter-script result JSONs in `results/` "
               "(dependency edges listed per test below).\n")

    out.append("\n## Quick reference table\n")
    out.append("| test | lines | runtime (s) | status | params | writes |")
    out.append("|---|---|---|---|---|---|")
    for name, t in sorted(reg.items()):
        m = meta.get(name, {})
        res = ", ".join(m.get("results_files_touched", [])[:2]) or "—"
        out.append(f"| {name} | {t['lines']} | {m.get('duration_s', '—')} "
                   f"| {m.get('status', '—')} | {len(t['params'])} | {res} |")

    out.append("\n## Per-test detail\n")
    for name, t in sorted(reg.items()):
        m = meta.get(name, {})
        out.append(f"### {name}")
        out.append(f"*{t['description']}*\n")
        out.append(f"- **file**: `{t['file']}` ({t['lines']} lines)")
        out.append(f"- **runtime**: {m.get('duration_s', 'n/a')}s "
                   f"(baseline status: {m.get('status', 'n/a')})")
        if t["depends"]:
            out.append(f"- **depends on**: {', '.join(t['depends'])} "
                       "(must run first — produces required result JSON)")
        if t["network"]:
            out.append("- **network**: fetches reference corpora from Project Gutenberg")
        if m.get("results_files_touched"):
            out.append(f"- **writes**: {', '.join('results/' + f for f in m['results_files_touched'])}")
        if t["params"]:
            plist = ", ".join(f"`{k}={json.dumps(v['default']) if v['type']=='json' else v['default']}`"
                              if len(str(v['default'])) < 40 else f"`{k}=<{v['type']}>`"
                              for k, v in t["params"].items())
            out.append(f"- **parameters** ({len(t['params'])}): {plist}")
        note = notes_for(name)
        if note:
            out.append("- **notes**:")
            for ln in note.splitlines():
                out.append(f"  {ln}")
        out.append("")

    (ROOT / "INVENTORY.md").write_text("\n".join(out) + "\n", encoding="utf-8")
    print(f"Wrote INVENTORY.md ({len(out)} lines) for {len(reg)} tests")


if __name__ == "__main__":
    main()
